language: node_js
node_js:
  - "0.10"
before_script:
  - "npm install -g pm2"
  - "pm2 start service/main.js -- -port=8080 --name pabtc-api -o commonlog.log -e commonlog.log"
  - "sleep 3"
after_script:
  - "pm2 stop all"
  - cat ~/.pm2/logs/commonlog.log
services: mongodb