language: node_js
node_js:
  - "0.10"
before_script:
  - "sleep 5"
  - "mongo --eval \"db.keys.insert({key: 'mockKey'})\""
  - "export NODE_ENV='local'"
  - "echo $NODE_ENV"
  - "npm install -g pm2"
  - "pm2 start service/main.js --name pa-btc"
  - "sleep 3"
after_script:
  - "pm2 stop all"
services: mongodb