language: node_js
node_js:
  - "0.10"
before_script:
  - "mongo --eval \"db.keys.insert({key: 'mockKey'})\""
  - "set ENV='local'"
  - "export ENV"
  - "npm install -g pm2"
  - "pm2 start service/main.js --name pabtc-api"
  - "sleep 3"
after_script:
  - "pm2 stop all"
services: mongodb