language: node_js
node_js:
  - "0.10"
before_script:
  - "mongo --eval \"db.keys.insert({key: 'mockKey'})\""
  - "set ENV='local'"
  - "export ENV"
  - "node service/main.js"
  - "sleep 3"
after_script:
services: mongodb